chinese/urls.py
from django.urls import path, include
from . import views
app_name = "chinese"
urlpatterns = [
    path('', views.index, name='chinese_index'),
    path('food_detail/<int:pk>', views.food_detail, name='food_detail'),
    path('food_delete/<int:pk>', views.food_delete, name='food_delete')
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("food/", include("chinese.urls")),
    path("customer/", include('customer.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path, include
from . import views

app_name = "customer"

urlpatterns = [

    path("", views.customer_index, name='customer_index'),
    path("food_detail/<int:pk>/", views.food_detail, name='food_detail'),
    # path("add_cart/", views.add_cart, name='add_cart'), # 장바구니 넣기
    # path('remove_cart/', views.remove_cart, name='remove_cart'),
    path('modify_cart/', views.modify_cart, name='modify_cart'), # 장바구니 빼기
]

chinese/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

class Food(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.TextField()
    image_url = models.URLField()

customer/models.py
from django.db import models
from chinese.models import Food
# Create your models here.

# 어떤 음식을 얼마나 카트에 담았나?

# 테이블 생성 디폴트 이름은 : customer_cart 프로젝토이름_클래스명
class Cart(models.Model):
    food = models.ForeignKey(Food, on_delete=models.DO_NOTHING)
    amount = models.IntegerField(default=0)

chinese/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Food, Category
from django.core.files.storage import FileSystemStorage
# Create your views here.

# def upload(request):
#     fs=FileSystemStorage()
#     uploaded_file = request.FILES['file']
#     name = fs.save(uploaded_file.name, uploaded_file)
#     url = fs.url(name)
#     return HttpResponse("{}에 저장이 잘 되었습니다.".format(url))

def index(request):
    # get(주소만 입력해서 오는 것) -> 페이지만 보여주고
    # post -> DB에 입력하는 과정을 넣자
    if request.method == 'GET':
        return render(request=request, template_name='chinese/index.html')
    
    elif request.method == 'POST':
        category = Category.objects.get(name=request.POST['category'])
        food_name = request.POST['foodname']
        food_price = request.POST['price']
        food_description = request.POST['description']
        food_takeout = request.POST['takeout']

        # 이미지 업로드
        fs = FileSystemStorage()
        uploaded_file = request.FILES['file']
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)

        Food.objects.create(category=category,
                            name=food_name,
                            price=food_price,
                            description=food_description,
                            image_url=url)
        return render(request=request, template_name='chinese/index.html')
    
def food_detail(request, pk):
    object = Food.objects.get(pk=pk)
    context = {
        'object':object
    }
    return render(request=request, template_name='chinese/food_detail.html', context=context)

def food_delete(request, pk):
    object = Food.objects.get(pk=pk)
    object.delete()
    return redirect('http://127.0.0.1:8000/')

config/views.py
from django.shortcuts import render
from chinese.models import Category, Food

def index(request):
    category = Category.objects.all()
    food = Food.objects.all()
    context = {
        'category':category,
        'food':food
    }
    return render(request=request, template_name='index.html', context=context)

customer/views.py
from django.shortcuts import render
from chinese.models import Category, Food 
from .models import Cart
# Create your views here.

def customer_index(request):
    # chinese의 모델 내용 사용해야함
    # 즉 다른 앱의 DB를 끌어와야 하는 것
    # 위에서 임포트를 통해 해결
    # 또한 카테고리만 보내면 푸드를 받아올 수 있다.
    category = Category.objects.all()
    context = {
        'category':category
    }
    return render(request, 'customer/index.html', context)

def food_detail(request, pk):
    # object 만들어야함
    food = Food.objects.get(pk=pk)
    context = {
        'object':food
    }
    return render(request, 'customer/customer_detail.html', context)

def add_cart(request):
    # 해당 food_id에 대응되는 데이터의 수량을 add하다 (하나 올려라)
    food_id = request.GET['food_id']
    food = Food.objects.get(pk=food_id)
    # 이전에 해당 음식에 대한 장바구니 정보가 있으면 get
    # 없으면 새로 생성해서 적용
    try:
        cart = Cart.objects.get(food=food)
    except:
        cart = Cart.objects.create(food=food)
    finally:
        pass
    cart.amount += 1
    cart.save()
    context = {
        'object':food
    }
    return render(request, 'customer/customer_detail.html', context)
    
def remove_cart(request):  
    food_id = request.GET['food_id']
    food = Food.objects.get(pk=food_id)
    cart, created = Cart.objects.get_or_create(food=food) # 새롭게 생성되었으면 created = True, 아니면 False 
    if cart.amount > 0:

        cart.amount -= 1
    else:
        cart.amount = 0

    cart.save()
    context = {
        'object':food
    }
    return render(request, 'customer/customer_detail.html', context)

from django.http import JsonResponse
def modify_cart(request):
    # 어떤 음식(food_id)에 amount를 amountChange만큼 변경하고
    # 변경된 최종 결과를 반환(JSON)
    food_id = request.POST['foodId']
    food = Food.objects.get(pk=food_id)
    cart, created = Cart.objects.get_or_create(food=food)
    cart.amount += int(request.POST['amountChange'])
    if cart.amount > 0:
        cart.save()
    
    context = {
        'newQuantity': cart.amount,
        'message':'수량이 성공적으로 업데이트 되었습니다.',
        'success':True
    }
    return JsonResponse(context)

chinese/templates/chinese/food_detail.html
<div class="container my-5">
    <h1 class="display-4 mb-3">{{ object.category.name }}</h1>
    <h2 class="mb-2">{{ object.name }}</h2>
    <h3 class="text-muted mb-3">{{ object.price }}원</h3>
    <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image mb-3">
    <p>{{ object.description }}</p>

    <form action="{% url 'chinese:food_delete' pk=object.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
    </form>

</div>

chinese/templates/chinese/index.html
<h1>Lion 중화요리에 오신 걸 환영해~</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="category">카테고리 선택:</label>
        <select name="category">
            <option value="면류">면류</option>
            <option value="밥류">밥류</option>
            <option value="요리류">요리류</option>
        </select>
    </div>
    <div>
        <label for="foodname">음식이름:</label>
        <input type="text" name="foodname">
    </div>
    <div>
        <label for="price">가격:</label>
        <input type="text" name="price">
    </div>
    <div>
        <label for="description">설명:</label>
        <textarea name="description" rows="4" cols="50"></textarea>
    </div>
    <div>
        <p>포장가능한 식품?</p>
        <input type="radio" name="takeout" value="yes">
        <label for="onlytakeout">포장만 가능</label><br>
        <input type="radio" name="takeout" value="no">
        <label for="cannottakeout">매장식사만 가능</label>
    </div>
    <div>
        <label for="file">사진을 올려주세요</label>
        <input type="file" name="file">
    </div>

    <input type="submit" value="제출">
</form>

customer/templates/customer/customer_detail.html
<h1>food detail</h1>


<div class="container my-5">
    <h1 class="display-4 mb-3">{{ object.category.name }}</h1>
    <h2 class="mb-2">{{ object.name }}</h2>
    <h3 class="text-muted mb-3">{{ object.price }}원</h3>
    <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image mb-3">
    <p>{{ object.description }}</p>
</div>

<div  class="container">
    <input type="hidden" id="csrfToken" value="{{csrf_token}}">
    <button type="button" onclick="modifyCartAmount({{object.id}}, 1)">담기</button>
    <button type="button" onclick="modifyCartAmount({{object.id}}, -1)">빼기</button>
<div>
    현재 수량 : <span id="currentQuantity"></span>
</div>
</div>
<!--
<div>
    input의 type 인자를 hidden을 이용하여 보내는 방법
    request에서 받아야함
    {# <form action="{% url 'customer:add_cart'  %}"> #}
    {#    <input type="hidden" name="food_id" value="{{object.id}}"> #}
        <button type="submit">담기</button>
    </form>
    인자로 보내는 방법, url에서 받아서 연계, url: add_cart/<int:pk>/ 이런 형태
    {# <form action="{% url 'customer:add_cart'  %}"> #}
    {#    <input type="hidden" name="food_id" value="{{object.id}}"> #}
    {#    <buttom type="submit">담기</buttom> #}
    {#</form> #}
</div>

<div>
{#    <form action="{% url 'customer:remove_cart'  %}"> #}
{#        <input type="hidden" name="food_id" value="{{object.id}}"> #}
        <button type="submit">빼기</button>
    </form>
</div>

<div>
{#    {{object.cart_set.all.0.amount}} #}
</div>-->

<script>
    function getCsrfToken(){
        return document.getElementById('csrfToken').value;
    }
    function modifyCartAmount(food_id, change){
        var xhr = new XMLHttpRequest();
            xhr.open('POST', '{% url "customer:modify_cart" %}', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', getCsrfToken());

            xhr.onload = function() {
                if (this.status === 200) {
                    var response = JSON.parse(this.responseText);
                    document.getElementById('currentQuantity').textContent = response.newQuantity;
                    console.log('Update successful:', response.message);
                } else {
                    console.error('Error updating:', this.statusText);
                }
            };
            xhr.send(`foodId=${food_id}&amountChange=${change}`);
    }
</script>

customer/templates/customer/index.html
<h1>고객페이지에 오신 것을 환영합니다.</h1>

<title>중화요리집</title>



<div>
    <h3>카테고리</h3>
    <ul>
        {% for cate in category %}
        <li>{{cate.name}}</li>
            {% for food in cate.food_set.all %}
            <a href="{% url 'customer:food_detail' pk=food.id %}">
                <img src="{{ food.image_url }}">
                <h5>{{ food.name }}</h5>
            {% endfor %}
        {% endfor %}
    </ul>
</div>

templates/index.html
<h1>우리 중화요리 집</h1>

<div>
    <a href="{% url 'chinese:chinese_index' %}">제품등록</a>
</div>

<div>
    <a href="{% url 'customer:customer_index' %}">고객페이지로 이동</a>
</div>

<div>
    <h3>카테고리</h3>
    <ul>
        {% for cate in category %}
        <li>{{cate.name}}</li>
        {% endfor %}
    </ul>
</div>
<div>
    <h3>음식</h3>
    {% for f in food %}
    <a href="{% url 'chinese:food_detail' pk=f.id %}">
        <img src="{{ f.image_url }}">
        <h5>{{ f.name }}</h5>
    </a>
    {% endfor %}
</div>